version: '3'
services:
  database:
    image: 'mongo'
    container_name: 'go-mongodb'
    environment:
      - MONGO_INITDB_DATABASE=gocoockbook
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'
